"""empty message

Revision ID: 04458a8f77ce
Revises: 0db519c3a2f0
Create Date: 2018-11-08 17:23:30.535022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04458a8f77ce'
down_revision = '0db519c3a2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dish_variant_menuparagraph_id_fkey', 'dish_variant', type_='foreignkey')
    op.drop_column('dish_variant', 'menuparagraph_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_variant', sa.Column('menuparagraph_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('dish_variant_menuparagraph_id_fkey', 'dish_variant', 'menuparagraph', ['menuparagraph_id'], ['id'])
    # ### end Alembic commands ###
