"""empty message

Revision ID: 0db519c3a2f0
Revises: 15bb165ae999
Create Date: 2018-11-08 17:09:22.104221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db519c3a2f0'
down_revision = '15bb165ae999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('menuparagraph_id', sa.Integer(), nullable=True))
    op.drop_constraint('dish_menu_paragraph_id_fkey', 'dish', type_='foreignkey')
    op.create_foreign_key(None, 'dish', 'menuparagraph', ['menuparagraph_id'], ['id'])
    op.drop_column('dish', 'menu_paragraph_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('menu_paragraph_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dish', type_='foreignkey')
    op.create_foreign_key('dish_menu_paragraph_id_fkey', 'dish', 'menuparagraph', ['menu_paragraph_id'], ['id'])
    op.drop_column('dish', 'menuparagraph_id')
    # ### end Alembic commands ###
