"""empty message

Revision ID: 15bb165ae999
Revises: 418dba43647a
Create Date: 2018-11-08 15:51:35.404148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15bb165ae999'
down_revision = '418dba43647a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text', sa.Column('restaurant_id', sa.Integer(), nullable=False))
    op.add_column('text', sa.Column('text', sa.TEXT(), nullable=False))
    op.create_foreign_key(None, 'text', 'restaurant', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'text', type_='foreignkey')
    op.drop_column('text', 'text')
    op.drop_column('text', 'restaurant_id')
    # ### end Alembic commands ###
