"""Init Active Text Association class

Revision ID: 170f153bf165
Revises: b3f1651dbff3
Create Date: 2018-11-13 17:21:54.305633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170f153bf165'
down_revision = 'b3f1651dbff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_active',
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['text_id'], ['text.id'], ),
    sa.PrimaryKeyConstraint('restaurant_id', 'text_id')
    )
    op.drop_table('texts_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts_active',
    sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], name='texts_active_restaurant_id_fkey'),
    sa.ForeignKeyConstraint(['text_id'], ['text.id'], name='texts_active_text_id_fkey'),
    sa.PrimaryKeyConstraint('restaurant_id', 'text_id', name='texts_active_pkey')
    )
    op.drop_table('text_active')
    # ### end Alembic commands ###
