"""empty message

Revision ID: 418dba43647a
Revises: 4ae9817c1c78
Create Date: 2018-11-08 14:23:13.517673

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '418dba43647a'
down_revision = '4ae9817c1c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text', sa.Column('created', sa.DateTime, default=datetime.utcnow,
               nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text', 'created')
    # ### end Alembic commands ###
