"""empty message

Revision ID: 4ae9817c1c78
Revises: 62d65e76cb92
Create Date: 2018-11-08 14:22:32.426349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ae9817c1c78'
down_revision = '62d65e76cb92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('text_restaurant_id_fkey', 'text', type_='foreignkey')
    op.drop_column('text', 'restaurant_id')
    op.drop_column('text', 'created')
    op.drop_column('text', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('text', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('text', sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('text_restaurant_id_fkey', 'text', 'restaurant', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###
