"""rename dish - dish_variant relationsship: step1: delete column

Revision ID: 58289df13978
Revises: 7995860c02c9
Create Date: 2018-11-13 12:26:30.929513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58289df13978'
down_revision = '7995860c02c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dish_variant_dish_id_fkey', 'dish_variant', type_='foreignkey')
    op.drop_column('dish_variant', 'dish_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_variant', sa.Column('dish_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('dish_variant_dish_id_fkey', 'dish_variant', 'dish', ['dish_id'], ['id'])
    # ### end Alembic commands ###
