"""empty message

Revision ID: 62d65e76cb92
Revises: e2254b805bcb
Create Date: 2018-11-08 13:00:48.951366

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62d65e76cb92'
down_revision = 'e2254b805bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('text', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('text', 'created')
    # ### end Alembic commands ###
