"""empty message

Revision ID: 66253fff5084
Revises: cec676e15818
Create Date: 2018-11-20 12:21:00.315431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66253fff5084'
down_revision = 'cec676e15818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_variant', sa.Column('position', sa.Integer(), nullable=True))
    op.alter_column('restaurant', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('restaurant', 'city_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('restaurant', 'street',
               existing_type=sa.VARCHAR(length=180),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'street',
               existing_type=sa.VARCHAR(length=180),
               nullable=True)
    op.alter_column('restaurant', 'city_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('restaurant', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('dish_variant', 'position')
    # ### end Alembic commands ###
