"""empty message

Revision ID: 71245f0e2bd9
Revises: d3d034b358d9
Create Date: 2018-12-08 13:15:30.204401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71245f0e2bd9'
down_revision = 'd3d034b358d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('restaurant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'owner', 'restaurant', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'owner', type_='foreignkey')
    op.drop_column('owner', 'restaurant_id')
    # ### end Alembic commands ###
