"""empty message

Revision ID: 7581b6a51e99
Revises: fb37befa5998
Create Date: 2018-11-04 19:42:32.664649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7581b6a51e99'
down_revision = 'fb37befa5998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('text_active', postgresql.ARRAY(sa.Integer), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'text_active')
    # ### end Alembic commands ###
