"""restaurant and dishvariant relationship

Revision ID: 7e14c43e8e8e
Revises: 04458a8f77ce
Create Date: 2018-11-08 17:25:28.630619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e14c43e8e8e'
down_revision = '04458a8f77ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dish_variant_restaurant_id_fkey', 'dish_variant', type_='foreignkey')
    op.drop_column('dish_variant', 'restaurant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_variant', sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('dish_variant_restaurant_id_fkey', 'dish_variant', 'restaurant', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###
