"""rename dish - dish_variant relationsship: step1: add columns again

Revision ID: 7faed0b3a49a
Revises: 58289df13978
Create Date: 2018-11-13 12:27:11.655971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7faed0b3a49a'
down_revision = '58289df13978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_variant', sa.Column('dish_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'dish_variant', 'dish', ['dish_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dish_variant', type_='foreignkey')
    op.drop_column('dish_variant', 'dish_id')
    # ### end Alembic commands ###
