"""empty message

Revision ID: 9c16673233f2
Revises: 170f153bf165
Create Date: 2018-11-19 13:54:36.311297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c16673233f2'
down_revision = '170f153bf165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menuparagraph', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menuparagraph', 'position')
    # ### end Alembic commands ###
