"""empty message

Revision ID: a9499980d6fd
Revises: f0081286144c
Create Date: 2018-10-29 12:29:46.622870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9499980d6fd'
down_revision = 'f0081286144c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.add_column('owner', sa.Column('last_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_owner_first_name'), 'owner', ['first_name'], unique=False)
    op.create_index(op.f('ix_owner_last_name'), 'owner', ['last_name'], unique=False)
    op.drop_index('ix_owner_username', table_name='owner')
    op.drop_column('owner', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_owner_username', 'owner', ['username'], unique=True)
    op.drop_index(op.f('ix_owner_last_name'), table_name='owner')
    op.drop_index(op.f('ix_owner_first_name'), table_name='owner')
    op.drop_column('owner', 'last_name')
    op.drop_column('owner', 'first_name')
    # ### end Alembic commands ###
