"""add of column position in texts_active table

Revision ID: b3f1651dbff3
Revises: 08a086d56694
Create Date: 2018-11-13 15:53:52.886153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f1651dbff3'
down_revision = '08a086d56694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts_active', sa.Column('position', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('texts_active', 'position')
    # ### end Alembic commands ###
