"""empty message

Revision ID: b52a0d706a9d
Revises: 7e14c43e8e8e
Create Date: 2018-11-12 20:32:25.728086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52a0d706a9d'
down_revision = '7e14c43e8e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'measurement')
    op.drop_column('dish', 'price')
    op.alter_column('restaurant', 'name',
               existing_type=sa.VARCHAR(length=180),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'name',
               existing_type=sa.VARCHAR(length=180),
               nullable=True)
    op.add_column('dish', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('dish', sa.Column('measurement', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
