"""empty message

Revision ID: c2be0c8d8fda
Revises: 9c16673233f2
Create Date: 2018-11-19 19:10:40.648183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2be0c8d8fda'
down_revision = '9c16673233f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menuparagraph', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menuparagraph', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
