"""empty message

Revision ID: cec676e15818
Revises: 0a335283f4bd
Create Date: 2018-11-19 19:20:10.403788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec676e15818'
down_revision = '0a335283f4bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dish', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dish', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
