"""empty message

Revision ID: d3d034b358d9
Revises: 66253fff5084
Create Date: 2018-12-04 12:18:30.512962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d034b358d9'
down_revision = '66253fff5084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('password', sa.String(length=128), nullable=True))
    op.drop_column('owner', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('owner', 'password')
    # ### end Alembic commands ###
