"""empty message

Revision ID: d4c05960a402
Revises: 
Create Date: 2018-11-04 19:39:52.307672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4c05960a402'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('vegetarian', sa.Boolean(), nullable=True),
    sa.Column('vegan', sa.Boolean(), nullable=True),
    sa.Column('measurement', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('allergens', postgresql.ARRAY(sa.Enum('GLUTENHALTIGEGETREIDE', 'KREBSTIERE', 'EIER', 'FISCH', 'ERDNÜSSE', 'SOJABOHNEN', 'MILCH', 'SCHALENFRÜCHTE', 'SELLERIE', 'SENF', 'SESAMSAMEN', 'SCHWEFELDIOXIDSULFITE', 'LUPINEN', 'WEICHTIERE', name='allergentype')), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dish_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measurement', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menuparagraph',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_email'), 'owner', ['email'], unique=True)
    op.create_index(op.f('ix_owner_first_name'), 'owner', ['first_name'], unique=False)
    op.create_index(op.f('ix_owner_last_name'), 'owner', ['last_name'], unique=False)
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telephone', sa.String(length=40), nullable=True),
    sa.Column('street', sa.String(length=180), nullable=True),
    sa.Column('street_number', sa.String(length=20), nullable=True),
    sa.Column('city_code', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text')
    op.drop_table('restaurant')
    op.drop_index(op.f('ix_owner_last_name'), table_name='owner')
    op.drop_index(op.f('ix_owner_first_name'), table_name='owner')
    op.drop_index(op.f('ix_owner_email'), table_name='owner')
    op.drop_table('owner')
    op.drop_table('menuparagraph')
    op.drop_table('dish_variant')
    op.drop_table('dish')
    # ### end Alembic commands ###
