"""empty message

Revision ID: f0081286144c
Revises: 8a314f04ad98
Create Date: 2018-10-25 18:24:37.765521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0081286144c'
down_revision = '8a314f04ad98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('menuparagraph_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'dish', 'menu__paragraph', ['menuparagraph_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dish', type_='foreignkey')
    op.drop_column('dish', 'menuparagraph_id')
    # ### end Alembic commands ###
