"""empty message

Revision ID: fb37befa5998
Revises: d4c05960a402
Create Date: 2018-11-04 19:41:22.037567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb37befa5998'
down_revision = 'd4c05960a402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('menu_paragraph_id', sa.Integer(), nullable=True))
    op.add_column('dish', sa.Column('restaurant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'dish', 'menuparagraph', ['menu_paragraph_id'], ['id'])
    op.create_foreign_key(None, 'dish', 'restaurant', ['restaurant_id'], ['id'])
    op.add_column('dish_variant', sa.Column('dish_id', sa.Integer(), nullable=False))
    op.add_column('dish_variant', sa.Column('menuparagraph_id', sa.Integer(), nullable=False))
    op.add_column('dish_variant', sa.Column('restaurant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'dish_variant', 'dish', ['dish_id'], ['id'])
    op.create_foreign_key(None, 'dish_variant', 'restaurant', ['restaurant_id'], ['id'])
    op.create_foreign_key(None, 'dish_variant', 'menuparagraph', ['menuparagraph_id'], ['id'])
    op.add_column('menuparagraph', sa.Column('restaurant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'menuparagraph', 'restaurant', ['restaurant_id'], ['id'])
    op.add_column('text', sa.Column('restaurant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'text', 'restaurant', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'text', type_='foreignkey')
    op.drop_column('text', 'restaurant_id')
    op.drop_constraint(None, 'menuparagraph', type_='foreignkey')
    op.drop_column('menuparagraph', 'restaurant_id')
    op.drop_constraint(None, 'dish_variant', type_='foreignkey')
    op.drop_constraint(None, 'dish_variant', type_='foreignkey')
    op.drop_constraint(None, 'dish_variant', type_='foreignkey')
    op.drop_column('dish_variant', 'restaurant_id')
    op.drop_column('dish_variant', 'menuparagraph_id')
    op.drop_column('dish_variant', 'dish_id')
    op.drop_constraint(None, 'dish', type_='foreignkey')
    op.drop_constraint(None, 'dish', type_='foreignkey')
    op.drop_column('dish', 'restaurant_id')
    op.drop_column('dish', 'menu_paragraph_id')
    # ### end Alembic commands ###
